### ISSUE TITLE
HTTP PATCH verb support

### ISSUE THREAD

**Issue by tenorz007** [dfurtado/pyterrier#5]
I noticed that there is no support for PATCH requests.

**Comment by dfurtado** [comment]
Hi, you are right. There is no support for PATCH yet. Correct me if I'm mistaken, it seems like implementation wise the PATCH would be very similar to PUT (if not the same) so it would be very simple to make accept PATCH and route it to the function that handles PUT requests.
I know that other frameworks for example Flask let you specify multiple HTTP verbs for a specific route.
That is something that I've been thinking about implementing as well, for example, adding an extra parameter in the route registration decorator with a list of secondary accepted HTTP verbs.
Do you have anything in your mind about how this could be implemented?

**Comment by tenorz007** [comment]
Yeah, PATCH requests would basically be implemented just as you did PUT and DELETE, using POST.
Concerning specifying multiple HTTP verbs for a route, I take it you want to have some form of route collector decorator; 
```python
@route('/', methods=['GET', 'POST'])
def index(self):
    pass
```
What do you think?

**Comment by dfurtado** [comment]
Something like that! However not with the strings 'GET' and 'POST', I try to not have so much magic strings and use types instead, that's the reason I added @app.get, put, delete, post instead of creating a @route like Flask.

One possible solution would be passing the decorator functions for example:

```python
@app.put('/update', additional_methods=[app.patch])
def update(self):
    pass
```

Then in the code that register the route would executes the additional methods decorators, passing the same route to it.

**Comment by tenorz007** [comment]
So I created a new issue #6 so we can discuss this there, as this goes beyond the scope of this issue.
But yes, I understand what you are trying to do. Perhaps we can come up with a good structure

**Comment by tenorz007** [comment]
The feature hasn't been implemented, should this be closed?
